name: Daily Check

on:
  schedule:
  # scheduled at 5:30am (UTC+8), weekdays
    - cron: "15 15 * * *"
  workflow_dispatch:

env:
  # ACTIONS_ALLOW_UNSECURE_COMMANDS: true

permissions:
  contents: write

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Run Python Code
        env:
          #TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python daily_check.py

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and push if changed
        run: |
          git add data/last_level.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last level [skip ci]" && git push)
